---
- name: Configure MOTD on Cisco Router
  hosts: "{{ target }}"
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Set MOTD Banner
      cisco.ios.ios_banner:
        banner: motd
        text: "{{ motd_message }}"
      register: motd_result

    - name: Show result
      debug:
        msg: "{{ motd_result }}"
