---
- name: Configure or Read MOTD on Cisco Routers
  hosts: routers
  gather_facts: no
  vars:
    # ตัวแปรที่จะถูกส่งจาก python ansible_final.py
    motd_message: ""
    configure: false
  tasks:

    - name: Configure MOTD if requested
      cisco.ios.ios_config:
        lines:
          - "banner motd {{ motd_message }}"
      when: configure | bool
      register: config_result

    - name: Return success message after configuration
      debug:
        msg: "Ok: success"
      when: configure | bool
      changed_when: true
      run_once: true

    - name: Read MOTD if configure is false
      cisco.ios.ios_command:
        commands:
          - show run | include banner
      register: motd_out
      when: not configure | bool

    - name: Return current MOTD
      debug:
        msg: >-
          {% if motd_out.stdout[0] != "" %}
            {{ motd_out.stdout[0] | regex_replace('^banner motd ', '') }}
          {% else %}
            Error: No MOTD Configured
          {% endif %}
      when: not configure | bool
      changed_when: false
      run_once: true
