- name: Configure or show MOTD
  hosts: routers
  gather_facts: no
  vars:
    motd_message: ""
    configure: false
  tasks:

    - name: Configure MOTD
      when: configure | bool
      cisco.ios.ios_config:
        lines:
          - "banner motd {{ motd_message }}"
      register: motd_config
      ignore_errors: yes

    - name: Show MOTD
      when: not configure | bool
      cisco.ios.ios_command:
        commands:
          - "show running-config | include banner motd"
      register: motd_result
      ignore_errors: yes

    - name: Set result message
      set_fact:
        result_message: >-
          {% if configure | bool %}
            Ok: success
          {% elif motd_result.stdout is defined and motd_result.stdout and motd_result.stdout[0] != '' %}
            {{ motd_result.stdout[0] | regex_replace('banner motd ', '') | trim }}
          {% else %}
            Error: No MOTD Configured
          {% endif %}
